name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd ./SRS/
        pip install -r requirements.txt

    - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: HRKU-d2b77430-83c5-4f8c-bdca-2221ef2d0ff4
        run: |
          heroku create student-registration-system --buildpack heroku/python
          git push heroku deployment